name: Run Postman collection
on: workflow_dispatch
jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the main branch
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
    - name: Install Newman
      run: npm install -g newman
    - name: Run Postman collection
      run: newman run myCollection.json || echo "Error Ocuured"
 

