name: Run Postman collection
on: workflow_dispatch
jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the main branch
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra
    - name: Run Postman collection
      run: newman run myCollection.json -n 20 -r htmlextra --reporter-htmlextra-export index.html || echo "Error Ocuured"
    - name: Configure git user
      run: |
        git config user.email "yashk.ug19.cs@nitp.ac.in"
        git config user.name "Yash-Kr"
    - name: Commit and push the changes
      run: |
        git add index.html
        git commit -m "Add newman html report"
        git push https://${{ secrets.PUSH_TOKEN }}@github.com/Yash-Kr/PostmanDemo main
 

