name: Run Postman collection
on: workflow_dispatch
jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the main branch
      uses: actions/checkout@v2
    - name: Install Node.js
      run: |
        echo "installing node"
        curl -sL https://deb.nodesource.com/setup_14.x | bash -
        apt-get install -y nodejs
    - name: Install Newman
      run: npm install newman
    - name: Run Postman collection
      run: npx newman run myCollection.json
      env:
        NEWMAN_LOG: verbose
    - name: Log the output
      run: echo "Newman run complete. Check the logs for details"
